services:
  db:
    build: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
    networks:
      - backup
    ports:
      - "3306:3306"

networks:
  backup:
    driver: bridge